from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

RiskLevel = Literal["low", "medium", "high", "block"]
DiffStatus = Literal["added", "modified", "deleted", "renamed"]
FindingSeverity = Literal["info", "low", "medium", "high", "critical"]


DEFAULT_CRITICAL_PATHS = [
    "auth/**",
    "security/**",
    "payments/**",
    "infra/**",
    ".github/workflows/**",
    "Dockerfile",
    "docker-compose.yml",
    "package.json",
    "pyproject.toml",
    "requirements*.txt",
]

DEFAULT_TEST_PATTERNS = [
    "tests/**",
    "**/*test*",
    "**/*spec*",
]

DEFAULT_AGENT_BRANCH_PATTERNS = [
    "copilot/**",
    "cursor/**",
    "devin/**",
    "codex/**",
    "claude/**",
]

DEFAULT_PR_BODY_MARKERS = [
    "Generated by",
    "Co-authored-by: Copilot",
    "Created by Devin",
]


class StrictConfigModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class LargeDiffConfig(StrictConfigModel):
    max_files: int = Field(default=20, gt=0)
    max_lines: int = Field(default=800, gt=0)


class RiskConfig(StrictConfigModel):
    fail_level: RiskLevel = "high"
    large_diff: LargeDiffConfig = Field(default_factory=LargeDiffConfig)


class AgentDetectionConfig(StrictConfigModel):
    branch_patterns: list[str] = Field(default_factory=lambda: DEFAULT_AGENT_BRANCH_PATTERNS.copy())
    pr_body_markers: list[str] = Field(default_factory=lambda: DEFAULT_PR_BODY_MARKERS.copy())

    @field_validator("branch_patterns", "pr_body_markers")
    @classmethod
    def validate_non_blank_values(cls, values: list[str]) -> list[str]:
        return _validate_non_blank_strings(values)


class RulesConfig(StrictConfigModel):
    require_tests_for_code_changes: bool = True
    flag_dependency_changes: bool = True
    flag_ci_changes: bool = True
    flag_auth_changes: bool = True
    flag_large_generated_files: bool = True


class AIConfig(StrictConfigModel):
    enabled: bool = False
    provider: str | None = None
    model: str | None = None
    base_url: str | None = None
    timeout_seconds: float = Field(default=15.0, gt=0, le=120)
    max_diff_chars: int = Field(default=12000, gt=0, le=50000)


class PluginConfig(StrictConfigModel):
    id: str
    enabled: bool = False
    permissions: list[str] = Field(default_factory=list)
    timeout_seconds: float = Field(default=5.0, gt=0, le=60)


class AgentReviewConfig(StrictConfigModel):
    version: int = 1
    risk: RiskConfig = Field(default_factory=RiskConfig)
    critical_paths: list[str] = Field(default_factory=lambda: DEFAULT_CRITICAL_PATHS.copy())
    test_patterns: list[str] = Field(default_factory=lambda: DEFAULT_TEST_PATTERNS.copy())
    agent_detection: AgentDetectionConfig = Field(default_factory=AgentDetectionConfig)
    rules: RulesConfig = Field(default_factory=RulesConfig)
    ai: AIConfig = Field(default_factory=AIConfig)
    plugins: list[PluginConfig] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_supported_version(self) -> AgentReviewConfig:
        if self.version != 1:
            raise ValueError("unsupported config version: expected version 1")
        return self

    @field_validator("critical_paths", "test_patterns")
    @classmethod
    def validate_patterns(cls, values: list[str]) -> list[str]:
        return _validate_non_blank_strings(values)


def _validate_non_blank_strings(values: list[str]) -> list[str]:
    for value in values:
        if not value.strip():
            raise ValueError("patterns and markers must not contain blank values")
    return values


class AddedDiffLine(StrictConfigModel):
    content: str
    line_number: int | None = Field(default=None, ge=1)


class DiffFile(StrictConfigModel):
    path: str
    status: DiffStatus
    additions: int = Field(default=0, ge=0)
    deletions: int = Field(default=0, ge=0)
    previous_path: str | None = None
    language: str | None = None
    is_test_file: bool = False
    is_critical_file: bool = False
    added_lines: list[AddedDiffLine] = Field(default_factory=list, exclude=True)


class RiskFinding(StrictConfigModel):
    rule_id: str
    severity: FindingSeverity
    title: str
    description: str
    score_delta: int
    file_path: str | None = None
    line_start: int | None = Field(default=None, ge=1)
    line_end: int | None = Field(default=None, ge=1)
    evidence: dict[str, Any] = Field(default_factory=dict)


class RiskAnalysis(StrictConfigModel):
    risk_score: int = Field(ge=0, le=100)
    risk_level: RiskLevel
    findings: list[RiskFinding] = Field(default_factory=list)
