from pathlib import Path

import pytest

from agentreview.config import ConfigError, load_config, parse_config
from agentreview.models import AgentReviewConfig


def test_load_valid_config(tmp_path: Path) -> None:
    config_path = tmp_path / ".agentreview.yml"
    config_path.write_text(
        """
version: 1
risk:
  fail_level: medium
  large_diff:
    max_files: 5
    max_lines: 120
critical_paths:
  - "billing/**"
test_patterns:
  - "tests/**"
agent_detection:
  branch_patterns:
    - "codex/**"
  pr_body_markers:
    - "Generated by"
rules:
  require_tests_for_code_changes: false
  flag_dependency_changes: true
  flag_ci_changes: true
  flag_auth_changes: true
  flag_large_generated_files: false
ai:
  enabled: true
  provider: fake
plugins:
  - id: dependency-manifest
    enabled: true
    permissions:
      - read_diff
    timeout_seconds: 2
""",
        encoding="utf-8",
    )

    config = load_config(config_path)

    assert config.version == 1
    assert config.risk.fail_level == "medium"
    assert config.risk.large_diff.max_files == 5
    assert config.risk.large_diff.max_lines == 120
    assert config.critical_paths == ["billing/**"]
    assert config.test_patterns == ["tests/**"]
    assert config.agent_detection.branch_patterns == ["codex/**"]
    assert config.rules.require_tests_for_code_changes is False
    assert config.rules.flag_large_generated_files is False
    assert config.ai.enabled is True
    assert config.ai.provider == "fake"
    assert config.plugins[0].id == "dependency-manifest"
    assert config.plugins[0].permissions == ["read_diff"]


def test_missing_config_uses_defaults(tmp_path: Path) -> None:
    config = load_config(tmp_path / ".agentreview.yml")

    assert isinstance(config, AgentReviewConfig)
    assert config.version == 1
    assert config.risk.fail_level == "high"
    assert config.risk.large_diff.max_files == 20
    assert config.risk.large_diff.max_lines == 800
    assert "auth/**" in config.critical_paths
    assert "tests/**" in config.test_patterns
    assert config.rules.require_tests_for_code_changes is True
    assert config.ai.enabled is False
    assert config.plugins == []


def test_example_config_loads() -> None:
    project_root = Path(__file__).parents[1]

    config = load_config(project_root / ".agentreview.example.yml")

    assert config.version == 1
    assert config.risk.fail_level == "high"
    assert ".github/workflows/**" in config.critical_paths


def test_invalid_version_fails_clearly() -> None:
    with pytest.raises(ConfigError, match="unsupported config version"):
        parse_config({"version": 2})


def test_invalid_risk_threshold_fails_clearly() -> None:
    with pytest.raises(ConfigError, match="max_files"):
        parse_config({"version": 1, "risk": {"large_diff": {"max_files": 0}}})


def test_blank_pattern_fails_clearly() -> None:
    with pytest.raises(ConfigError, match="blank values"):
        parse_config({"version": 1, "critical_paths": ["auth/**", " "]})


def test_non_mapping_config_fails_clearly(tmp_path: Path) -> None:
    config_path = tmp_path / ".agentreview.yml"
    config_path.write_text("- not\n- a\n- mapping\n", encoding="utf-8")

    with pytest.raises(ConfigError, match="expected a YAML mapping"):
        load_config(config_path)
